### ISSUE TITLE
Parquet errors when step name contains a `/` character

### ISSUE THREAD

**Issue by db-ks** [opentap/Parquet#28] opened 2023-11-28 08:05 UTC
**Environment**
[A link to the Environment where the bug was found](https://test-automation.dev.pw.keysight.com/)

**Describe the bug**
Parquet is unable to find a file and gets removed

**To Reproduce**
1. Add Dialog step
2. Select Cloud Drive image
3. Run TestPlan
4. Answer the Dialog

**Actual behavior**
Parquet ResultListener throws an exception and gets removed

**Expected behavior**
Parquet ResultListener to now throw an exception and get removed

**Screenshots**

![image](https://github.com/opentap/ks8500/assets/18167872/68572116-a817-4bba-a22d-02973517bde0)

**Additional context**

Logs: 

```
13:47:43.649     Session                   Session log loaded as 'C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\SessionLogs\tap 2023-11-27 12-47-43.txt'. [11.3 ms]
13:47:43.667     Session                   Running '"C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\tap.exe" runner session --id 52173bb8-7f35-4173-a1fb-7990305dbf25 --nats-server nats://127.0.0.1:20222 --log "C:\Runner2\SessionLogs" --creds "SUAITR3UO4YONOK5WVNUE6A33HJJ64H2WFLKGIQ3BHQRD6WQYCBVNJ6AAM
13:47:43.710     AssemblyFinder            Found 11/61 assembly files. [15.2 ms]
13:47:43.724     Resolver                  Found match for System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\System.Collections.Immutable.1.2.3.0\System.Collections.Immutable.dll
13:47:43.748     Resolver                  Found match for System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\System.Reflection.Metadata.1.4.3.0\System.Reflection.Metadata.dll
13:47:43.854     Searcher                  Ordered 11 assemblies according to references. [117 ms]
13:47:43.915     PluginManager             Found 8 plugin assemblies containing 208 plugin types. [180 ms]
13:47:43.916     PluginManager             Found version 9.22.2+1f88c8b1  of OpenTap.dll
13:47:43.916     PluginManager             Found version 9.22.2+1f88c8b1  of OpenTap.Package.dll
13:47:43.916     PluginManager             Found version 0.2.0+7e7541d6   of Keysight.OpenTap.CloudDrive.dll
13:47:43.916     PluginManager             Found version 9.0.6+e89e1ec1   of OpenTap.Plugins.Demo.Battery.dll
13:47:43.916     PluginManager             Found version 9.0.6+e89e1ec1   of OpenTap.Plugins.Demo.ResultsAndTiming.dll
13:47:43.916     PluginManager             Found version 9.22.2+1f88c8b1  of OpenTap.Plugins.BasicSteps.dll
13:47:43.916     PluginManager             Found version 0.1.3-beta.6+37cac20d of OpenTap.Plugins.Parquet.dll
13:47:43.916     PluginManager             Found version 1.7.0-rc.1+abd14746 of OpenTap.Runner.dll
13:47:43.916     PluginManager             Searched 11 Assemblies. [183 ms]
13:47:43.941     AssemblyData              Loaded OpenTap. [378 us]
13:47:43.959     SystemInfo                Microsoft Windows 10.0.22621 X64
13:47:43.959     SystemInfo                .NET Framework 4.8.9181.0
13:47:43.960     SystemInfo                OpenTAP Engine 9.22.2+1f88c8b1 X64
13:47:43.962     AssemblyData              Loaded OpenTap.Package. [2.88 ms]
13:47:43.985     Settings                  No settings file exists for EngineSettings. A new instance with default values has been created. [10.4 ms]
13:47:44.005     AssemblyData              Loaded OpenTap.Plugins.BasicSteps. [3.44 ms]
13:47:44.007     AssemblyData              Loaded Keysight.OpenTap.CloudDrive. [5.34 ms]
13:47:44.027     Session                   Session log loaded as 'C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\SessionLogs\SessionLog 2023-11-27 12-47-43.txt'. [17.0 ms]
13:47:44.037     AssemblyData              Loaded OpenTap.Runner. [3.25 ms]
12:47:44.076     AssemblyData              Loaded mscorlib. [200 ns]
12:47:44.155     CLI                       The CLI option '--log' from 'OpenTap.Runner.CliActions.SessionCliAction' overrides a common CLI option from OpenTAP.
12:47:44.157     CLI                       Executing CLI action: runner \ session
12:47:44.166     Resolver                  Found match for NATS.Client, Version=1.0.8.0, Culture=neutral, PublicKeyToken=5b58bc7249e111a9 in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\NATS.Client.1.0.8.0\NATS.Client.dll
12:47:44.233     Installation              Cloud Drive   - 0.2.0+7e7541d6
12:47:44.233     Installation              Demonstration - 9.0.6+e89e1ec1
12:47:44.233     Installation              OpenTAP       - 9.22.2+1f88c8b1
12:47:44.233     Installation              Parquet       - 0.1.3-beta.6+37cac20d
12:47:44.233     Installation              Runner        - 1.7.0-rc.1+abd14746
12:47:44.244     Settings                  No settings file exists for AuthenticationSettings. A new instance with default values has been created. [531 us]
12:47:44.250     Resolver                  Found match for Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10 in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\Serilog.2.0.0.0\Serilog.dll
12:47:44.254     Resolver                  Found match for OpenTap.NATS.Service, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\OpenTap.NATS.Service.0.1.0.0\OpenTap.NATS.Service.dll
12:47:44.258     Resolver                  Found match for OpenTap.NATS, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\OpenTap.NATS.0.1.0.0\OpenTap.NATS.dll
12:47:44.266     Resolver                  Found match for NATS.Client, Version=1.0.3.0, Culture=neutral, PublicKeyToken=5b58bc7249e111a9 in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\NATS.Client.1.0.8.0\NATS.Client.dll
12:47:44.268     Resolver                  Found match for Serilog.Sinks.Console, Version=4.1.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10 in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\Serilog.Sinks.Console.4.1.0.0\Serilog.Sinks.Console.dll
12:47:44.272     Resolver                  Found match for Serilog.Sinks.File, Version=5.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10 in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\Serilog.Sinks.File.5.0.0.0\Serilog.Sinks.File.dll
12:47:44.339     Resolver                  Found match for Serilog.Formatting.Compact, Version=1.1.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10 in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\Serilog.Formatting.Compact.1.1.0.0\Serilog.Formatting.Compact.dll
12:47:44.379     Session                   Session log loaded as 'C:\Runner2\SessionLogs\Session-52173bb8-7f35-4173-a1fb-7990305dbf25-2023-27-11-12-47.txt'. [26.2 ms]
12:47:44.380     Session                   Running '"C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\tap.exe" runner session --id 52173bb8-7f35-4173-a1fb-7990305dbf25 --nats-server nats://127.0.0.1:20222 --log "C:\Runner2\SessionLogs" --creds "SUAITR3UO4YONOK5WVNUE6A33HJJ64H2WFLKGIQ3BHQRD6WQYCBVNJ6AAM
12:47:44.488     Resolver                  Found match for Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\Newtonsoft.Json.12.0.0.0\Newtonsoft.Json.dll
12:47:44.653     Runner                    This Runner is registered as 'UBUSQHL2F2CWWI645EZERKENXKZSCYMOWUBDBIF2EQHKF2T23RKVIPZH' (D9D6EA9CAB2A24B4)
12:47:44.691     Settings                  No settings file exists for DutSettings. A new instance with default values has been created. [2.62 ms]
12:47:44.691     Settings                  No settings file exists for InstrumentSettings. A new instance with default values has been created. [351 us]
12:47:44.692     Settings                  No settings file exists for ConnectionSettings. A new instance with default values has been created. [384 us]
12:47:44.692     Settings                  No settings file exists for ResultSettings. A new instance with default values has been created. [393 us]
12:47:44.694     Settings                  No settings file exists for CloudDriveSettings. A new instance with default values has been created. [1.37 ms]
12:47:45.134     Resolver                  Found match for NJsonSchema, Version=10.6.10.0, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102 in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\NJsonSchema.10.6.10.0\NJsonSchema.dll
12:47:45.138     Resolver                  Found match for Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\Newtonsoft.Json.12.0.0.0\Newtonsoft.Json.dll
12:47:45.290     Resolver                  Found match for System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\System.Memory.4.0.1.1\System.Memory.dll
12:47:45.298     Resolver                  Found match for System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\System.Runtime.CompilerServices.Unsafe.6.0.0.0\System.Runtime.CompilerServices.Unsafe.dll
13:47:45.399     AssemblyData              Loaded OpenTap.Plugins.Demo.ResultsAndTiming. [3.47 ms]
13:47:45.403     Settings                  DutSettings loaded from C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Settings\Bench\Default\DUTs.xml [12.6 ms]
13:47:45.448     Settings                  EngineSettings loaded from C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Settings\Engine.xml [44.4 ms]
13:47:45.452     AssemblyData              Loaded OpenTap.Plugins.Demo.Battery. [3.57 ms]
13:47:45.456     Settings                  InstrumentSettings loaded from C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Settings\Bench\Default\Instruments.xml [8.50 ms]
13:47:45.456     Settings                  ConnectionSettings loaded from C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Settings\Bench\Default\Connections.xml [253 us]
13:47:45.461     AssemblyData              Loaded OpenTap.Plugins.Parquet. [3.92 ms]
13:47:45.465     Settings                  ResultSettings loaded from C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Settings\Results.xml [8.36 ms]
13:47:45.471     Settings                  CloudDriveSettings loaded from C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Settings\Cloud Drive.xml [5.84 ms]
13:47:47.046     CLI                       Executing CLI action: package \ check-updates
13:47:47.056     Settings                  No settings file exists for PackageManagerSettings. A new instance with default values has been created. [2.02 ms]
13:47:47.056     CLI                       CLI action returned exit code: 0 [10.1 ms]
14:11:29.718     AssemblyFinder            Found 11/61 assembly files. [25.1 ms]
14:11:29.719     Resolver                  Found match for System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\System.Text.Json.4.0.1.0\System.Text.Json.dll
14:11:30.424     Resolver                  Found match for System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\System.Buffers.4.0.3.0\System.Buffers.dll
14:11:30.456     Resolver                  Found match for System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\System.Numerics.Vectors.4.1.4.0\System.Numerics.Vectors.dll
14:11:30.489     Resolver                  Found match for System.Runtime.CompilerServices.Unsafe, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\System.Runtime.CompilerServices.Unsafe.4.0.6.0\System.Runtime.CompilerServices.Unsafe.dll
14:11:30.536     CloudDrive                Request: /api/packages/4.0/Objects/users/dennis/bluescreen.png?version=1.0.0
14:11:31.434     CloudDrive                Saved file to C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\CloudDrive\users\dennis\bluescreen.png
14:23:33.905     AssemblyData              Loaded System.Core. [300 ns]
14:26:31.256     TestPlan                  -----------------------------------------------------------------
14:26:31.307     TestPlan                  Starting TestPlan 'BasicSteps' on 11/27/2023 13:26:31, 12 of 12 TestSteps enabled.
14:26:31.393     TestPlan                  Saved Test Plan XML [13.9 ms]
14:26:31.400     Settings                  No settings file exists for TestPlanRunPackageParameterMonitor. A new instance with default values has been created. [242 us]
14:26:31.467     ParquetResultListener     Resource "ParquetResultListener" opened. [4.96 ms]
14:26:31.514     TestPlan                  PrePlanRun Methods completed [8.35 ms]
14:26:31.537     TestPlan                  "Delay 2 s" started.
14:26:33.566     TestPlan                  "Delay 2 s" completed. [2.02 s]
14:26:33.568     TestPlan                  "Run 'tap.exe package list -i'" started.
14:26:33.576     TestStep                  Starting process tap.exe with arguments "package list -i"
14:26:33.603     AssemblyFinder            Found 11/61 assembly files. [31.7 ms]
14:26:33.604     Resolver                  Found match for Parquet, Version=3.0.0.0, Culture=neutral, PublicKeyToken=d380b3dee6d01926 in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\Parquet.3.0.0.0\Parquet.dll
14:26:34.550     TestStep                  OUTPUT:  Cloud Drive   - 0.2.0+7e7541d6        - installed
14:26:34.550     TestStep                  OUTPUT:  Demonstration - 9.0.6+e89e1ec1        - installed
14:26:34.550     TestStep                  OUTPUT:  OpenTAP       - 9.22.2+1f88c8b1       - installed
14:26:34.550     TestStep                  OUTPUT:  Parquet       - 0.1.3-beta.6+37cac20d - installed
14:26:34.550     TestStep                  OUTPUT:  Runner        - 1.7.0-rc.1+abd14746   - installed
14:26:34.572     TestPlan                  "Run 'tap.exe package list -i'" completed with verdict 'Pass'. [1.00 s]
14:26:34.572     TestPlan                  "Delay 2 s" started.
14:26:36.580     TestPlan                  "Delay 2 s" completed. [2.00 s]
14:26:36.580     TestPlan                  "Log Output" started.
14:26:36.581     TestStep                  
14:26:36.581     TestPlan                  "Log Output" completed. [1.38 ms]
14:26:36.581     TestPlan                  "Dialog CloudDrive/users/dennis/bluescreen.png" started.
14:26:41.604     TestPlan                  "Dialog CloudDrive/users/dennis/bluescreen.png" completed with verdict 'Inconclusive'. [5.02 s]
14:26:41.604     TestPlan                  "Parallel" started.
14:26:41.605     TestPlan                  Error at Step Run Completed for ParquetResultListener
14:26:41.608     TestStep                  Starting 2 child steps in separate threads.
14:26:41.610     TestPlan                  DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Results\BasicSteps23-11-27-13-26-31\Dialog CloudDrive\users\dennis\bluescreen.png.parquet'.
14:26:41.612     TestPlan                  "Parallel \ Sequence (1)" started.
14:26:41.612     TestPlan                  "Parallel \ Sequence" started.
14:26:41.619     TestPlan                  "Parallel \ Sequence (1) \ Lock (1)" started.
14:26:41.619     TestPlan                  "Parallel \ Sequence \ Lock" started.
14:26:41.621     TestPlan                  "Parallel \ Sequence \ Lock \ Delay 5 s" started.
14:26:41.794     TestPlan                      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
14:26:41.794     TestPlan                      at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
14:26:41.794     TestPlan                      at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
14:26:41.794     TestPlan                      at OpenTap.Plugins.Parquet.ParquetFile..ctor(Schema schema, String path)
14:26:41.794     TestPlan                      at OpenTap.Plugins.Parquet.ParquetResultListener.GetOrCreateParquetFile(Schema schema, String suggestedPath)
14:26:41.794     TestPlan                      at OpenTap.Plugins.Parquet.ParquetResultListener.OnTestStepRunCompleted(TestStepRun stepRun)
14:26:41.794     TestPlan                      at OpenTap.TestPlanRun.<>c__DisplayClass55_0.<AddTestStepRunCompleted>b__0(IResultListener listener)
14:26:41.795     TestPlan                  Exception caught at:
14:26:41.801     TestPlan                      at Void WorkerFunction()
14:26:41.801     TestPlan                      at Void Process()
14:26:41.801     TestPlan                      at Void processQueue()
14:26:41.801     TestPlan                      at Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
14:26:41.801     TestPlan                      ...
14:26:41.887     AssemblyFinder            Found 11/61 assembly files. [13.6 ms]
14:26:41.888     Resolver                  Found match for IronSnappy, Version=1.3.0.0, Culture=neutral, PublicKeyToken=b1d4b1dc83bdcf31 in C:\Users\Runner.Sprinter.000\AppData\Local\Temp\opentap-images\6BAB9DE7634852FFC6D2F09E2EAF4225056BA877\Dependencies\IronSnappy.1.3.0.0\IronSnappy.dll
14:26:41.995     TestPlan                  Removing faulty ResultListener 'ParquetResultListener'
14:26:46.632     TestPlan                  "Parallel \ Sequence \ Lock \ Delay 5 s" completed. [5.01 s]
14:26:46.635     TestPlan                  "Parallel \ Sequence \ Lock" completed. [5.01 s]
14:26:46.635     TestPlan                  "Parallel \ Sequence" completed. [5.02 s]
14:26:46.635     TestPlan                  "Parallel \ Sequence (1) \ Lock (1) \ Delay 5 s" started.
14:26:51.646     TestPlan                  "Parallel \ Sequence (1) \ Lock (1) \ Delay 5 s" completed. [5.01 s]
14:26:51.646     TestPlan                  "Parallel \ Sequence (1) \ Lock (1)" completed. [10.0 s]
14:26:51.646     TestPlan                  "Parallel \ Sequence (1)" completed. [10.0 s]
14:26:51.646     TestPlan                  "Parallel" completed. [10.0 s]
14:26:51.647     TestPlan                  Test step runs finished. [20.1 s]
14:26:51.685     Summary                   -------------- Summary of test plan started 11/27/2023 13:26:31 --------------
14:26:51.688     Summary                    Delay 2 s                                              2.02 s          
14:26:51.688     Summary                    Run 'tap.exe package list -i'                          1.00 s   Pass   
14:26:51.688     Summary                    Delay 2 s                                              2.00 s          
14:26:51.688     Summary                    Log Output                                             1.38 ms         
14:26:51.688     Summary                    Dialog CloudDrive/users/dennis/bluescreen.png            5.02 s   Inconclusive
14:26:51.688     Summary                    Parallel                                               10.0 s          
14:26:51.688     Summary                      Sequence (1)                                         10.0 s          
14:26:51.688     Summary                        Lock (1)                                           10.0 s          
14:26:51.688     Summary                          Delay 5 s                                        5.01 s          
14:26:51.688     Summary                      Sequence                                             5.02 s          
14:26:51.688     Summary                        Lock                                               5.01 s          
14:26:51.688     Summary                          Delay 5 s                                        5.01 s          
14:26:51.688     Summary                   ------------------------------------------------------------------------------
14:26:51.689     Summary                   ---------- Test plan completed with verdict Inconclusive in 20.3 s -----------
14:26:51.713     ParquetResultListener     Resource "ParquetResultListener" closed. [19.7 us]
```

**Comment by frederikja163** [comment] 2023-11-28 08:24
I think this might be fixed in the latest version. As of right now i cant reproduce this on the main branch using KS8400, however as there are problems with the KS8500 UI I'm unable to test if its the same there.

**Comment by jfaaborg** [comment] 2023-11-28 10:03
@frederikja163  why can't you test it? KS8500 UI should be functional.

**Comment by sebastian-pop** [comment] 2023-11-28 12:17
I have verified this on DEV with the latest Parquet beta and I can confirm it's fixed

**Closed** 2023-11-28 15:07 UTC
Labels: bug

**Comment by sebastian-pop** [comment] 2023-12-06 14:57
Fix confirmed 


![Image](https://github.com/opentap/Parquet/assets/97734470/e917a422-d267-4e22-83e7-6083d3f3f198)
